#!/usr/bin/env python3
"""Held-out calibration report for the optional solo reach-30 critic.

The input must be trajectories generated by a frozen critic-bearing checkpoint on
an episode-disjoint seed block. Predictions are actor-time values; targets/horizon
are post-game metadata on the final row. Every episode has equal total weight.
"""

from __future__ import annotations

import argparse
import json
import math
from collections import defaultdict
from pathlib import Path
from typing import Any

import numpy as np

from ppo import binary_auc, binary_average_precision, binary_ece


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--data", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--horizon", type=int, default=30)
    parser.add_argument("--bins", type=int, default=10)
    parser.add_argument("--bootstrap", type=int, default=2000)
    parser.add_argument("--seed", type=int, default=20260713)
    return parser.parse_args()


def load_episodes(data_dir: Path, expected_horizon: int) -> tuple[list[list[dict]], int, int]:
    episodes: dict[str, list[dict]] = defaultdict(list)
    rows_seen = rows_with_prediction = 0
    for path in sorted(data_dir.rglob("*.jsonl")):
        if path.name.startswith("games-"):
            continue
        with path.open() as handle:
            for line in handle:
                try:
                    row = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if not isinstance(row, dict) or "gameId" not in row:
                    continue
                rows_seen += 1
                prediction = row.get("reach30Pred")
                if isinstance(prediction, (int, float)) and math.isfinite(prediction):
                    rows_with_prediction += 1
                episodes[str(row["gameId"])].append(row)

    valid: list[list[dict]] = []
    for game_id, raw_rows in episodes.items():
        rows = sorted(raw_rows, key=lambda row: int(row.get("stepIdx", -1)))
        if [row.get("stepIdx") for row in rows] != list(range(len(rows))):
            raise ValueError(f"{game_id}: non-contiguous stepIdx")
        final = rows[-1]
        if final.get("reach30Target") not in (0, 1):
            raise ValueError(f"{game_id}: missing final reach30Target")
        if final.get("reach30Horizon") != expected_horizon:
            raise ValueError(
                f"{game_id}: reach30Horizon={final.get('reach30Horizon')} "
                f"!= expected {expected_horizon}"
            )
        if any("reach30Target" in row or "reach30Horizon" in row for row in rows[:-1]):
            raise ValueError(f"{game_id}: outcome metadata appears before final row")
        predicted = []
        for row in rows:
            value = row.get("reach30Pred")
            if not isinstance(value, (int, float)) or not math.isfinite(value):
                continue
            if not 0 <= float(value) <= 1:
                raise ValueError(f"{game_id}: reach30Pred outside [0,1]")
            if not isinstance(row.get("round"), (int, float)) or not isinstance(
                row.get("vp"), (int, float)
            ):
                raise ValueError(f"{game_id}: prediction row missing round/vp diagnostics")
            predicted.append(row)
        if not predicted:
            raise ValueError(f"{game_id}: no reach30 predictions")
        predicted = [dict(row) for row in predicted]
        predicted[-1]["reach30Target"] = final["reach30Target"]
        valid.append(predicted)
    if not valid:
        raise ValueError(f"no labelled reach30 episodes found under {data_dir}")
    return valid, rows_seen, rows_with_prediction


def flatten(episodes: list[list[dict]]) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    targets: list[float] = []
    scores: list[float] = []
    weights: list[float] = []
    for rows in episodes:
        target = float(rows[-1]["reach30Target"])
        weight = 1.0 / len(rows)
        for row in rows:
            targets.append(target)
            scores.append(float(row["reach30Pred"]))
            weights.append(weight)
    return np.asarray(targets), np.asarray(scores), np.asarray(weights)


def reliability(
    targets: np.ndarray, scores: np.ndarray, weights: np.ndarray, bins: int
) -> list[dict[str, Any]]:
    indices = np.minimum((scores * bins).astype(np.int64), bins - 1)
    output = []
    for index in range(bins):
        mask = indices == index
        weight = float(weights[mask].sum())
        output.append(
            {
                "lo": index / bins,
                "hi": (index + 1) / bins,
                "episodeWeight": weight,
                "rows": int(mask.sum()),
                "meanPrediction": float(np.average(scores[mask], weights=weights[mask]))
                if weight
                else None,
                "observedRate": float(np.average(targets[mask], weights=weights[mask]))
                if weight
                else None,
            }
        )
    return output


def metrics(episodes: list[list[dict]], bins: int) -> dict[str, Any]:
    targets, scores, weights = flatten(episodes)
    clipped = np.clip(scores, 1e-7, 1 - 1e-7)
    per_nll = -(targets * np.log(clipped) + (1 - targets) * np.log(1 - clipped))
    base_rate = float(np.mean([rows[-1]["reach30Target"] for rows in episodes]))
    constant = np.full_like(scores, base_rate)
    constant_clipped = np.clip(constant, 1e-7, 1 - 1e-7)
    constant_nll = -(targets * np.log(constant_clipped) + (1 - targets) * np.log(1 - constant_clipped))
    def finite(value: float) -> float | None:
        return float(value) if math.isfinite(float(value)) else None

    return {
        "episodes": len(episodes),
        "rows": int(scores.size),
        "baseRate": base_rate,
        "nll": float(np.average(per_nll, weights=weights)),
        "brier": float(np.average((scores - targets) ** 2, weights=weights)),
        "auc": finite(binary_auc(targets, scores, weights)),
        "auprc": finite(binary_average_precision(targets, scores, weights)),
        "ece": finite(binary_ece(targets, scores, bins=bins, weights=weights)),
        "sharpnessStd": float(np.sqrt(np.average((scores - np.average(scores, weights=weights)) ** 2, weights=weights))),
        "constantBaseRate": {
            "nll": float(np.average(constant_nll, weights=weights)),
            "brier": float(np.average((constant - targets) ** 2, weights=weights)),
        },
        "reliability": reliability(targets, scores, weights, bins),
    }


def slice_episodes(
    episodes: list[list[dict]], predicate
) -> list[list[dict]]:
    sliced = []
    for episode in episodes:
        rows = [row for row in episode if predicate(row)]
        if rows:
            # Preserve the episode's final target on the last selected row.
            rows = [dict(row) for row in rows]
            rows[-1]["reach30Target"] = episode[-1]["reach30Target"]
            sliced.append(rows)
    return sliced


def bootstrap_episode_means(
    episodes: list[list[dict]], draws: int, seed: int
) -> dict[str, list[float]]:
    episode_nll = []
    episode_brier = []
    for rows in episodes:
        target = float(rows[-1]["reach30Target"])
        scores = np.asarray([float(row["reach30Pred"]) for row in rows])
        clipped = np.clip(scores, 1e-7, 1 - 1e-7)
        episode_nll.append(float(np.mean(-(target * np.log(clipped) + (1 - target) * np.log(1 - clipped)))))
        episode_brier.append(float(np.mean((scores - target) ** 2)))
    rng = np.random.default_rng(seed)
    indices = rng.integers(0, len(episodes), size=(draws, len(episodes)))
    nll_draws = np.asarray(episode_nll)[indices].mean(axis=1)
    brier_draws = np.asarray(episode_brier)[indices].mean(axis=1)
    return {
        "nll95": np.quantile(nll_draws, [0.025, 0.975]).tolist(),
        "brier95": np.quantile(brier_draws, [0.025, 0.975]).tolist(),
    }


def main() -> None:
    args = parse_args()
    episodes, rows_seen, rows_with_prediction = load_episodes(args.data, args.horizon)
    report: dict[str, Any] = {
        "schemaVersion": "reach30-calibration-v1",
        "data": str(args.data),
        "horizon": args.horizon,
        "episodes": len(episodes),
        "rowsSeen": rows_seen,
        "rowsWithPrediction": rows_with_prediction,
        "predictionCoverage": rows_with_prediction / rows_seen if rows_seen else 0.0,
        "overall": metrics(episodes, args.bins),
        "bootstrapByEpisode": bootstrap_episode_means(
            episodes, args.bootstrap, args.seed
        ),
    }
    round_slices = {
        "early_1_10": lambda row: 1 <= int(row.get("round", 0)) <= 10,
        "mid_11_20": lambda row: 11 <= int(row.get("round", 0)) <= 20,
        "late_21_30": lambda row: 21 <= int(row.get("round", 0)) <= 30,
    }
    vp_slices = {
        "vp_under15": lambda row: float(row.get("vp", -1)) < 15,
        "vp_15_24": lambda row: 15 <= float(row.get("vp", -1)) < 25,
        "vp_25_29": lambda row: 25 <= float(row.get("vp", -1)) < 30,
    }
    report["roundSlices"] = {
        name: metrics(selected, args.bins)
        for name, predicate in round_slices.items()
        if (selected := slice_episodes(episodes, predicate))
    }
    report["vpSlices"] = {
        name: metrics(selected, args.bins)
        for name, predicate in vp_slices.items()
        if (selected := slice_episodes(episodes, predicate))
    }
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(report, indent=2, allow_nan=False) + "\n")
    print(json.dumps(report["overall"], indent=2, allow_nan=False))
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
