#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

RUN_ID="${RUN_ID:-nonfallen-farmq-$(date -u +%Y%m%dT%H%M%SZ)}"
OUT_DIR="ml/meta_runs/$RUN_ID"
DATA_DIR="$OUT_DIR/data"
LOG_DIR="$OUT_DIR/logs"

GAMES="${GAMES:-16}"
SEATS="${SEATS:-4}"
MAX_WINDOWS="${MAX_WINDOWS:-256}"
MAX_ROUNDS="${MAX_ROUNDS:-30}"
MIN_ROUND="${MIN_ROUND:-0}"
MAX_ROUND_FILTER="${MAX_ROUND_FILTER:-20}"
HORIZONS="${HORIZONS:-3,6,10,15}"
LABEL_HORIZON="${LABEL_HORIZON:-10}"
LABEL_STATUS_TOLERANCE="${LABEL_STATUS_TOLERANCE:-1}"
VALUE_SCALE_VP="${VALUE_SCALE_VP:-3}"
POLICY_WEIGHT="${POLICY_WEIGHT:-0}"
KILL_THRESHOLD="${KILL_THRESHOLD:-0.5}"
MIN_OPPORTUNITY_VP="${MIN_OPPORTUNITY_VP:-1}"
MIN_MONSTER_HP="${MIN_MONSTER_HP:-4}"
MAX_MONSTER_HP="${MAX_MONSTER_HP:-5}"
MAX_STATUS_LEVEL="${MAX_STATUS_LEVEL:-2}"
PROFILES="${PROFILES:-paragon,farmer,farmer2,hard}"

mkdir -p "$DATA_DIR" "$LOG_DIR"

echo "== non-Fallen FarmQ counterfactual =="
echo "run_id=$RUN_ID games=$GAMES seats=$SEATS max_windows=$MAX_WINDOWS"
echo "monster_hp=$MIN_MONSTER_HP..$MAX_MONSTER_HP status_cap=$MAX_STATUS_LEVEL rounds=$MIN_ROUND..$MAX_ROUND_FILTER profiles=$PROFILES"
echo "value_scale_vp=$VALUE_SCALE_VP policy_weight=$POLICY_WEIGHT"
echo "out_dir=$OUT_DIR"

env \
  FARMQ=1 \
  FARMQ_GAMES="$GAMES" \
  FARMQ_SEATS="$SEATS" \
  FARMQ_MAXROUNDS="$MAX_ROUNDS" \
  FARMQ_MAX_WINDOWS="$MAX_WINDOWS" \
  FARMQ_MIN_ROUND="$MIN_ROUND" \
  FARMQ_MAX_ROUND="$MAX_ROUND_FILTER" \
  FARMQ_HORIZONS="$HORIZONS" \
  FARMQ_LABEL_HORIZON="$LABEL_HORIZON" \
  FARMQ_LABEL_STATUS_TOLERANCE="$LABEL_STATUS_TOLERANCE" \
  FARMQ_VALUE_SCALE_VP="$VALUE_SCALE_VP" \
  FARMQ_POLICY_WEIGHT="$POLICY_WEIGHT" \
  FARMQ_KILL_THRESHOLD="$KILL_THRESHOLD" \
  FARMQ_MIN_OPPORTUNITY_VP="$MIN_OPPORTUNITY_VP" \
  FARMQ_MIN_MONSTER_HP="$MIN_MONSTER_HP" \
  FARMQ_MAX_MONSTER_HP="$MAX_MONSTER_HP" \
  FARMQ_QUALIFY_MAX_STATUS_LEVEL="$MAX_STATUS_LEVEL" \
  FARMQ_MAX_STATUS_LEVEL="$MAX_STATUS_LEVEL" \
  FARMQ_ALLOW_FIREPOWER_FARM=1 \
  FARMQ_ALLOW_CORRUPT_FARM=1 \
  FARMQ_FORBID_TYPES=initiatePvp \
  FARMQ_PROFILES="$PROFILES" \
  FARMQ_DATA_OUT="$DATA_DIR/farmq.jsonl" \
  FARMQ_OUT="$OUT_DIR/farmq.json" \
  FARMQ_SUMMARY="$OUT_DIR/summary.json" \
  npx vitest run src/lib/play/ml/_farmcounterfactual.test.ts --disable-console-intercept \
  2>&1 | tee "$LOG_DIR/farmq.log"

echo "DONE $OUT_DIR"
