#!/usr/bin/env bash
set -euo pipefail

HOST="${ARC_BOT_GPU_HOST:-ubuntu@216.151.21.122}"
REMOTE_DIR="${ARC_BOT_REMOTE_DIR:-/data/share8/michaelvuaprilexperimentation/arc-bot}"
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUN_ID="${RUN_ID:-tracestateq-fullcontrol-$(date -u +%Y%m%dT%H%M%SZ)}"
GPU="${GPU:-6}"
MIN_FREE_MB="${MIN_FREE_MB:-1024}"
SYNC="${SYNC:-1}"

WEIGHTS="${WEIGHTS:-ml/meta_runs/damage-contract-bootstrap-20260629T190011Z/best_policy.full.json}"
PATCH_NAV_WEIGHTS="${PATCH_NAV_WEIGHTS:-}"
PATCH_NAV_GATE="${PATCH_NAV_GATE:-hp2-survival-deficit}"
PATCH2_NAV_WEIGHTS="${PATCH2_NAV_WEIGHTS:-}"
PATCH2_NAV_GATE="${PATCH2_NAV_GATE:-all}"
NAV_WEIGHTS="${NAV_WEIGHTS:-ml/meta_runs/damage-contract-bootstrap-20260629T190011Z/nav_build_policy.json}"
NAV_GATE="${NAV_GATE:-unsafe-firepower-build-option}"
SCALE_NAV_WEIGHTS="${SCALE_NAV_WEIGHTS:-}"
SCALE_NAV_GATE="${SCALE_NAV_GATE:-route-option-scaling}"
MICRO_WEIGHTS="${MICRO_WEIGHTS:-}"
MICRO_GATE="${MICRO_GATE:-location-interactions}"
ROUTE_FINISH_ORACLE="${ROUTE_FINISH_ORACLE:-0}"
PROFILES="${PROFILES:-pvphunter,medium,cultivator,survivor}"
PLANNER_PROFILE="${PLANNER_PROFILE:-cultivator}"
SOURCE_SEED_BASE="${SOURCE_SEED_BASE:-6500000}"

GAMES="${GAMES:-16}"
MAX_WINDOWS="${MAX_WINDOWS:-64}"
MAX_ROUNDS="${MAX_ROUNDS:-30}"
HORIZONS="${HORIZONS:-6,12,18}"
LABEL_HORIZON="${LABEL_HORIZON:-12}"
MIN_SOURCE_VP="${MIN_SOURCE_VP:-0}"
MAX_SOURCE_VP="${MAX_SOURCE_VP:-24}"
MIN_PLAYER_VP="${MIN_PLAYER_VP:-9}"
MAX_PLAYER_VP="${MAX_PLAYER_VP:-24}"
MIN_ROUND="${MIN_ROUND:-8}"
MAX_ROUND="${MAX_ROUND:-}"
SOURCE_DESTINATION="${SOURCE_DESTINATION:-}"
MIN_MONSTER_HP="${MIN_MONSTER_HP:-4}"
MAX_MONSTER_HP="${MAX_MONSTER_HP:-}"
MIN_CLEAN_KILL_PROB="${MIN_CLEAN_KILL_PROB:-0}"
MAX_CLEAN_KILL_PROB="${MAX_CLEAN_KILL_PROB:-0.5}"
MIN_FIREPOWER_KILL_PROB="${MIN_FIREPOWER_KILL_PROB:-0}"
MAX_FIREPOWER_KILL_PROB="${MAX_FIREPOWER_KILL_PROB:-}"
REENTRY_BUILD_STEPS="${REENTRY_BUILD_STEPS:-2}"
SCRIPTS="${SCRIPTS:-policy,abyss-probe,restore-loop,max-barrier-loop,damage-assembly,hp4-survival-oracle,finish-line-oracle,fixed-reentry}"
ROLLOUT_POLICY="${ROLLOUT_POLICY:-policy}"
POSITIVE_ONLY_DATA="${POSITIVE_ONLY_DATA:-1}"
SAMPLE_MODE="${SAMPLE_MODE:-navigation}"
FULL_SAMPLE_TYPES="${FULL_SAMPLE_TYPES:-}"

LABEL_SCORE_THRESHOLD="${LABEL_SCORE_THRESHOLD:-0.5}"
LABEL_VP_THRESHOLD="${LABEL_VP_THRESHOLD:-0.5}"
LABEL_STATUS_TOLERANCE="${LABEL_STATUS_TOLERANCE:-0}"
SCORE_REACH30_BONUS="${SCORE_REACH30_BONUS:-12}"
SCORE_VP_WEIGHT="${SCORE_VP_WEIGHT:-1}"
SCORE_KILL_WEIGHT="${SCORE_KILL_WEIGHT:-0.5}"
SCORE_CLEAN_OPPORTUNITY_WEIGHT="${SCORE_CLEAN_OPPORTUNITY_WEIGHT:-2}"
SCORE_FIREPOWER_OPPORTUNITY_WEIGHT="${SCORE_FIREPOWER_OPPORTUNITY_WEIGHT:-0.5}"
SCORE_EXPECTED_ATTACK_WEIGHT="${SCORE_EXPECTED_ATTACK_WEIGHT:-1.2}"
SCORE_ATTACK_DICE_WEIGHT="${SCORE_ATTACK_DICE_WEIGHT:-0.8}"
SCORE_SPIRIT_ANIMAL_WEIGHT="${SCORE_SPIRIT_ANIMAL_WEIGHT:-0.8}"
SCORE_CULTIVATOR_WEIGHT="${SCORE_CULTIVATOR_WEIGHT:-0.4}"
SCORE_BARRIER_WEIGHT="${SCORE_BARRIER_WEIGHT:-0.4}"
SCORE_CURRENT_BARRIER_WEIGHT="${SCORE_CURRENT_BARRIER_WEIGHT:-1}"
SCORE_EXPOSURE_WINDOW_WEIGHT="${SCORE_EXPOSURE_WINDOW_WEIGHT:-0}"
SCORE_EXPOSURE_VP_WEIGHT="${SCORE_EXPOSURE_VP_WEIGHT:-0}"
SCORE_EXPOSURE_BEST_VP_WEIGHT="${SCORE_EXPOSURE_BEST_VP_WEIGHT:-0}"
EXPOSURE_MIN_VP="${EXPOSURE_MIN_VP:-12}"
EXPOSURE_MIN_MONSTER_HP="${EXPOSURE_MIN_MONSTER_HP:-4}"
REQUIRE_EXPOSURE_DELTA="${REQUIRE_EXPOSURE_DELTA:-0}"
SCORE_TARGET_QUALITY_WINDOW_WEIGHT="${SCORE_TARGET_QUALITY_WINDOW_WEIGHT:-0}"
SCORE_TARGET_QUALITY_VP_WEIGHT="${SCORE_TARGET_QUALITY_VP_WEIGHT:-0}"
SCORE_TARGET_QUALITY_BEST_VP_WEIGHT="${SCORE_TARGET_QUALITY_BEST_VP_WEIGHT:-0}"
TARGET_QUALITY_MIN_VP="${TARGET_QUALITY_MIN_VP:-18}"
REQUIRE_TARGET_QUALITY_DELTA="${REQUIRE_TARGET_QUALITY_DELTA:-0}"
SCORE_STATUS_PENALTY="${SCORE_STATUS_PENALTY:-2}"

FORBID_TYPES="${FORBID_TYPES:-initiatePvp}"
MAX_STATUS_LEVEL="${MAX_STATUS_LEVEL:-0}"
PRESERVE_ROUTE_FIREPOWER="${PRESERVE_ROUTE_FIREPOWER:-1}"
PRESERVE_ROUTE_SURVIVAL="${PRESERVE_ROUTE_SURVIVAL:-1}"
ITERS="${ITERS:-64}"
PLANNER_HORIZON="${PLANNER_HORIZON:-24}"
VALUEW="${VALUEW:-1}"
TIMEOUT="${TIMEOUT:-90m}"
PROGRESS_EVERY="${PROGRESS_EVERY:-4}"

TRAIN="${TRAIN:-0}"
MIN_TRAIN_SAMPLES="${MIN_TRAIN_SAMPLES:-12}"
TRAIN_INIT_WEIGHTS="${TRAIN_INIT_WEIGHTS:-$WEIGHTS}"
TRAIN_EPOCHS="${TRAIN_EPOCHS:-16}"
TRAIN_BATCH="${TRAIN_BATCH:-64}"
TRAIN_LR="${TRAIN_LR:-0.0003}"
TRAIN_VALUE_COEF="${TRAIN_VALUE_COEF:-0.25}"

if [[ "$SYNC" == "1" ]]; then
  (cd "$ROOT_DIR" && npm run bot:gpu:sync)
fi

REMOTE_SOURCE_DESTINATION="$(printf '%q' "$SOURCE_DESTINATION")"

set +e
ssh -o BatchMode=yes -o ConnectTimeout=8 "$HOST" \
  REMOTE_DIR="$REMOTE_DIR" \
  RUN_ID="$RUN_ID" \
  GPU="$GPU" \
  MIN_FREE_MB="$MIN_FREE_MB" \
  WEIGHTS="$WEIGHTS" \
  PATCH_NAV_WEIGHTS="$PATCH_NAV_WEIGHTS" \
  PATCH_NAV_GATE="$PATCH_NAV_GATE" \
  PATCH2_NAV_WEIGHTS="$PATCH2_NAV_WEIGHTS" \
  PATCH2_NAV_GATE="$PATCH2_NAV_GATE" \
  NAV_WEIGHTS="$NAV_WEIGHTS" \
  NAV_GATE="$NAV_GATE" \
  SCALE_NAV_WEIGHTS="$SCALE_NAV_WEIGHTS" \
  SCALE_NAV_GATE="$SCALE_NAV_GATE" \
  MICRO_WEIGHTS="$MICRO_WEIGHTS" \
  MICRO_GATE="$MICRO_GATE" \
  ROUTE_FINISH_ORACLE="$ROUTE_FINISH_ORACLE" \
  PROFILES="$PROFILES" \
  PLANNER_PROFILE="$PLANNER_PROFILE" \
  SOURCE_SEED_BASE="$SOURCE_SEED_BASE" \
  GAMES="$GAMES" \
  MAX_WINDOWS="$MAX_WINDOWS" \
  MAX_ROUNDS="$MAX_ROUNDS" \
  HORIZONS="$HORIZONS" \
  LABEL_HORIZON="$LABEL_HORIZON" \
  MIN_SOURCE_VP="$MIN_SOURCE_VP" \
  MAX_SOURCE_VP="$MAX_SOURCE_VP" \
  MIN_PLAYER_VP="$MIN_PLAYER_VP" \
  MAX_PLAYER_VP="$MAX_PLAYER_VP" \
  MIN_ROUND="$MIN_ROUND" \
  MAX_ROUND="$MAX_ROUND" \
  SOURCE_DESTINATION="$REMOTE_SOURCE_DESTINATION" \
  MIN_MONSTER_HP="$MIN_MONSTER_HP" \
  MAX_MONSTER_HP="$MAX_MONSTER_HP" \
  MIN_CLEAN_KILL_PROB="$MIN_CLEAN_KILL_PROB" \
  MAX_CLEAN_KILL_PROB="$MAX_CLEAN_KILL_PROB" \
  MIN_FIREPOWER_KILL_PROB="$MIN_FIREPOWER_KILL_PROB" \
  MAX_FIREPOWER_KILL_PROB="$MAX_FIREPOWER_KILL_PROB" \
  REENTRY_BUILD_STEPS="$REENTRY_BUILD_STEPS" \
  SCRIPTS="$SCRIPTS" \
  ROLLOUT_POLICY="$ROLLOUT_POLICY" \
  POSITIVE_ONLY_DATA="$POSITIVE_ONLY_DATA" \
  SAMPLE_MODE="$SAMPLE_MODE" \
  FULL_SAMPLE_TYPES="$FULL_SAMPLE_TYPES" \
  LABEL_SCORE_THRESHOLD="$LABEL_SCORE_THRESHOLD" \
  LABEL_VP_THRESHOLD="$LABEL_VP_THRESHOLD" \
  LABEL_STATUS_TOLERANCE="$LABEL_STATUS_TOLERANCE" \
  SCORE_REACH30_BONUS="$SCORE_REACH30_BONUS" \
  SCORE_VP_WEIGHT="$SCORE_VP_WEIGHT" \
  SCORE_KILL_WEIGHT="$SCORE_KILL_WEIGHT" \
  SCORE_CLEAN_OPPORTUNITY_WEIGHT="$SCORE_CLEAN_OPPORTUNITY_WEIGHT" \
  SCORE_FIREPOWER_OPPORTUNITY_WEIGHT="$SCORE_FIREPOWER_OPPORTUNITY_WEIGHT" \
  SCORE_EXPECTED_ATTACK_WEIGHT="$SCORE_EXPECTED_ATTACK_WEIGHT" \
  SCORE_ATTACK_DICE_WEIGHT="$SCORE_ATTACK_DICE_WEIGHT" \
  SCORE_SPIRIT_ANIMAL_WEIGHT="$SCORE_SPIRIT_ANIMAL_WEIGHT" \
  SCORE_CULTIVATOR_WEIGHT="$SCORE_CULTIVATOR_WEIGHT" \
  SCORE_BARRIER_WEIGHT="$SCORE_BARRIER_WEIGHT" \
  SCORE_CURRENT_BARRIER_WEIGHT="$SCORE_CURRENT_BARRIER_WEIGHT" \
  SCORE_EXPOSURE_WINDOW_WEIGHT="$SCORE_EXPOSURE_WINDOW_WEIGHT" \
  SCORE_EXPOSURE_VP_WEIGHT="$SCORE_EXPOSURE_VP_WEIGHT" \
  SCORE_EXPOSURE_BEST_VP_WEIGHT="$SCORE_EXPOSURE_BEST_VP_WEIGHT" \
  EXPOSURE_MIN_VP="$EXPOSURE_MIN_VP" \
  EXPOSURE_MIN_MONSTER_HP="$EXPOSURE_MIN_MONSTER_HP" \
  REQUIRE_EXPOSURE_DELTA="$REQUIRE_EXPOSURE_DELTA" \
  SCORE_TARGET_QUALITY_WINDOW_WEIGHT="$SCORE_TARGET_QUALITY_WINDOW_WEIGHT" \
  SCORE_TARGET_QUALITY_VP_WEIGHT="$SCORE_TARGET_QUALITY_VP_WEIGHT" \
  SCORE_TARGET_QUALITY_BEST_VP_WEIGHT="$SCORE_TARGET_QUALITY_BEST_VP_WEIGHT" \
  TARGET_QUALITY_MIN_VP="$TARGET_QUALITY_MIN_VP" \
  REQUIRE_TARGET_QUALITY_DELTA="$REQUIRE_TARGET_QUALITY_DELTA" \
  SCORE_STATUS_PENALTY="$SCORE_STATUS_PENALTY" \
  FORBID_TYPES="$FORBID_TYPES" \
  MAX_STATUS_LEVEL="$MAX_STATUS_LEVEL" \
  PRESERVE_ROUTE_FIREPOWER="$PRESERVE_ROUTE_FIREPOWER" \
  PRESERVE_ROUTE_SURVIVAL="$PRESERVE_ROUTE_SURVIVAL" \
  ITERS="$ITERS" \
  PLANNER_HORIZON="$PLANNER_HORIZON" \
  VALUEW="$VALUEW" \
  TIMEOUT="$TIMEOUT" \
  PROGRESS_EVERY="$PROGRESS_EVERY" \
  TRAIN="$TRAIN" \
  MIN_TRAIN_SAMPLES="$MIN_TRAIN_SAMPLES" \
  TRAIN_INIT_WEIGHTS="$TRAIN_INIT_WEIGHTS" \
  TRAIN_EPOCHS="$TRAIN_EPOCHS" \
  TRAIN_BATCH="$TRAIN_BATCH" \
  TRAIN_LR="$TRAIN_LR" \
  TRAIN_VALUE_COEF="$TRAIN_VALUE_COEF" \
  bash -s <<'REMOTE'
set -euo pipefail

cd "$REMOTE_DIR"
if test -s "$HOME/.nvm/nvm.sh"; then
  # shellcheck disable=SC1090
  source "$HOME/.nvm/nvm.sh"
  nvm use 22 >/dev/null
fi

if command -v nvidia-smi >/dev/null 2>&1; then
  free_mb="$(nvidia-smi --query-gpu=memory.free --format=csv,noheader,nounits -i "$GPU" | head -n 1 | tr -dc '0-9')"
  used_mb="$(nvidia-smi --query-gpu=memory.used --format=csv,noheader,nounits -i "$GPU" | head -n 1 | tr -dc '0-9')"
  echo "gpu=$GPU free_mb=${free_mb:-unknown} used_mb=${used_mb:-unknown} min_free_mb=$MIN_FREE_MB"
  if [[ -n "${free_mb:-}" && "$free_mb" -lt "$MIN_FREE_MB" ]]; then
    echo "refusing trace-state run: GPU $GPU has ${free_mb}MB free, below MIN_FREE_MB=$MIN_FREE_MB" >&2
    exit 2
  fi
fi

OUT_DIR="ml/meta_runs/$RUN_ID"
DATA_DIR="$OUT_DIR/data"
mkdir -p "$OUT_DIR/logs" "$DATA_DIR"

cat > "$OUT_DIR/config.json" <<JSON
{
  "run_id": "$RUN_ID",
  "mode": "trace-state-counterfactual",
  "gpu": "$GPU",
  "min_free_mb": $MIN_FREE_MB,
  "weights": "$WEIGHTS",
  "patch_nav_weights": "$PATCH_NAV_WEIGHTS",
  "patch_nav_gate": "$PATCH_NAV_GATE",
  "patch2_nav_weights": "$PATCH2_NAV_WEIGHTS",
  "patch2_nav_gate": "$PATCH2_NAV_GATE",
  "nav_weights": "$NAV_WEIGHTS",
  "nav_gate": "$NAV_GATE",
  "scale_nav_weights": "$SCALE_NAV_WEIGHTS",
  "scale_nav_gate": "$SCALE_NAV_GATE",
  "micro_weights": "$MICRO_WEIGHTS",
  "micro_gate": "$MICRO_GATE",
  "route_finish_oracle": "$ROUTE_FINISH_ORACLE",
  "profiles": "$PROFILES",
  "planner_profile": "$PLANNER_PROFILE",
  "source_seed_base": $SOURCE_SEED_BASE,
  "games": $GAMES,
  "max_windows": $MAX_WINDOWS,
  "max_rounds": $MAX_ROUNDS,
  "horizons": "$HORIZONS",
  "label_horizon": $LABEL_HORIZON,
  "source_vp_window": [$MIN_SOURCE_VP, $MAX_SOURCE_VP],
  "player_vp_window": [$MIN_PLAYER_VP, $MAX_PLAYER_VP],
  "min_round": $MIN_ROUND,
  "max_round": "$MAX_ROUND",
  "source_destination": "$SOURCE_DESTINATION",
  "monster_hp_window": ["$MIN_MONSTER_HP", "$MAX_MONSTER_HP"],
  "clean_kill_prob_window": ["$MIN_CLEAN_KILL_PROB", "$MAX_CLEAN_KILL_PROB"],
  "firepower_kill_prob_window": ["$MIN_FIREPOWER_KILL_PROB", "$MAX_FIREPOWER_KILL_PROB"],
  "reentry_build_steps": $REENTRY_BUILD_STEPS,
  "scripts": "$SCRIPTS",
  "rollout_policy": "$ROLLOUT_POLICY",
  "positive_only_data": "$POSITIVE_ONLY_DATA",
  "sample_mode": "$SAMPLE_MODE",
  "full_sample_types": "$FULL_SAMPLE_TYPES",
  "data_out": "$DATA_DIR/traceq.jsonl",
  "label_score_threshold": $LABEL_SCORE_THRESHOLD,
  "label_vp_threshold": $LABEL_VP_THRESHOLD,
  "label_status_tolerance": $LABEL_STATUS_TOLERANCE,
  "score_exposure_window_weight": $SCORE_EXPOSURE_WINDOW_WEIGHT,
  "score_exposure_vp_weight": $SCORE_EXPOSURE_VP_WEIGHT,
  "score_exposure_best_vp_weight": $SCORE_EXPOSURE_BEST_VP_WEIGHT,
  "exposure_min_vp": $EXPOSURE_MIN_VP,
  "exposure_min_monster_hp": $EXPOSURE_MIN_MONSTER_HP,
  "require_exposure_delta": "$REQUIRE_EXPOSURE_DELTA",
  "score_target_quality_window_weight": $SCORE_TARGET_QUALITY_WINDOW_WEIGHT,
  "score_target_quality_vp_weight": $SCORE_TARGET_QUALITY_VP_WEIGHT,
  "score_target_quality_best_vp_weight": $SCORE_TARGET_QUALITY_BEST_VP_WEIGHT,
  "target_quality_min_vp": $TARGET_QUALITY_MIN_VP,
  "require_target_quality_delta": "$REQUIRE_TARGET_QUALITY_DELTA",
  "forbid_types": "$FORBID_TYPES",
  "max_status_level": "$MAX_STATUS_LEVEL",
  "preserve_route_firepower": "$PRESERVE_ROUTE_FIREPOWER",
  "preserve_route_survival": "$PRESERVE_ROUTE_SURVIVAL",
  "iters": $ITERS,
  "planner_horizon": $PLANNER_HORIZON,
  "value_weight": $VALUEW,
  "train": "$TRAIN",
  "min_train_samples": $MIN_TRAIN_SAMPLES,
  "train_init_weights": "$TRAIN_INIT_WEIGHTS",
  "train_epochs": $TRAIN_EPOCHS,
  "train_batch": $TRAIN_BATCH,
  "train_lr": $TRAIN_LR,
  "train_value_coef": $TRAIN_VALUE_COEF
}
JSON

timeout "$TIMEOUT" env \
  CUDA_VISIBLE_DEVICES="$GPU" \
  TRACEQ=1 \
  TRACEQ_WEIGHTS="$WEIGHTS" \
  TRACEQ_PATCH_NAV_WEIGHTS="$PATCH_NAV_WEIGHTS" \
  TRACEQ_PATCH_NAV_GATE="$PATCH_NAV_GATE" \
  TRACEQ_PATCH2_NAV_WEIGHTS="$PATCH2_NAV_WEIGHTS" \
  TRACEQ_PATCH2_NAV_GATE="$PATCH2_NAV_GATE" \
  TRACEQ_NAV_WEIGHTS="$NAV_WEIGHTS" \
  TRACEQ_NAV_GATE="$NAV_GATE" \
  TRACEQ_SCALE_NAV_WEIGHTS="$SCALE_NAV_WEIGHTS" \
  TRACEQ_SCALE_NAV_GATE="$SCALE_NAV_GATE" \
  TRACEQ_MICRO_WEIGHTS="$MICRO_WEIGHTS" \
  TRACEQ_MICRO_GATE="$MICRO_GATE" \
  TRACEQ_ROUTE_FINISH_ORACLE="$ROUTE_FINISH_ORACLE" \
  TRACEQ_PROFILES="$PROFILES" \
  TRACEQ_PLANNER_PROFILE="$PLANNER_PROFILE" \
  TRACEQ_SOURCE_SEED_BASE="$SOURCE_SEED_BASE" \
  TRACEQ_GAMES="$GAMES" \
  TRACEQ_MAX_WINDOWS="$MAX_WINDOWS" \
  TRACEQ_MAXROUNDS="$MAX_ROUNDS" \
  TRACEQ_HORIZONS="$HORIZONS" \
  TRACEQ_LABEL_HORIZON="$LABEL_HORIZON" \
  TRACEQ_MIN_SOURCE_VP="$MIN_SOURCE_VP" \
  TRACEQ_MAX_SOURCE_VP="$MAX_SOURCE_VP" \
  TRACEQ_MIN_PLAYER_VP="$MIN_PLAYER_VP" \
  TRACEQ_MAX_PLAYER_VP="$MAX_PLAYER_VP" \
  TRACEQ_MIN_ROUND="$MIN_ROUND" \
  TRACEQ_MAX_ROUND="$MAX_ROUND" \
  TRACEQ_SOURCE_DESTINATION="$SOURCE_DESTINATION" \
  TRACEQ_MIN_MONSTER_HP="$MIN_MONSTER_HP" \
  TRACEQ_MAX_MONSTER_HP="$MAX_MONSTER_HP" \
  TRACEQ_MIN_CLEAN_KILL_PROB="$MIN_CLEAN_KILL_PROB" \
  TRACEQ_MAX_CLEAN_KILL_PROB="$MAX_CLEAN_KILL_PROB" \
  TRACEQ_MIN_FIREPOWER_KILL_PROB="$MIN_FIREPOWER_KILL_PROB" \
  TRACEQ_MAX_FIREPOWER_KILL_PROB="$MAX_FIREPOWER_KILL_PROB" \
  TRACEQ_REENTRY_BUILD_STEPS="$REENTRY_BUILD_STEPS" \
  TRACEQ_SCRIPTS="$SCRIPTS" \
  TRACEQ_ROLLOUT_POLICY="$ROLLOUT_POLICY" \
  TRACEQ_POSITIVE_ONLY_DATA="$POSITIVE_ONLY_DATA" \
  TRACEQ_SAMPLE_MODE="$SAMPLE_MODE" \
  TRACEQ_FULL_SAMPLE_TYPES="$FULL_SAMPLE_TYPES" \
  TRACEQ_LABEL_SCORE_THRESHOLD="$LABEL_SCORE_THRESHOLD" \
  TRACEQ_LABEL_VP_THRESHOLD="$LABEL_VP_THRESHOLD" \
  TRACEQ_LABEL_STATUS_TOLERANCE="$LABEL_STATUS_TOLERANCE" \
  TRACEQ_SCORE_REACH30_BONUS="$SCORE_REACH30_BONUS" \
  TRACEQ_SCORE_VP_WEIGHT="$SCORE_VP_WEIGHT" \
  TRACEQ_SCORE_KILL_WEIGHT="$SCORE_KILL_WEIGHT" \
  TRACEQ_SCORE_CLEAN_OPPORTUNITY_WEIGHT="$SCORE_CLEAN_OPPORTUNITY_WEIGHT" \
  TRACEQ_SCORE_FIREPOWER_OPPORTUNITY_WEIGHT="$SCORE_FIREPOWER_OPPORTUNITY_WEIGHT" \
  TRACEQ_SCORE_EXPECTED_ATTACK_WEIGHT="$SCORE_EXPECTED_ATTACK_WEIGHT" \
  TRACEQ_SCORE_ATTACK_DICE_WEIGHT="$SCORE_ATTACK_DICE_WEIGHT" \
  TRACEQ_SCORE_SPIRIT_ANIMAL_WEIGHT="$SCORE_SPIRIT_ANIMAL_WEIGHT" \
  TRACEQ_SCORE_CULTIVATOR_WEIGHT="$SCORE_CULTIVATOR_WEIGHT" \
  TRACEQ_SCORE_BARRIER_WEIGHT="$SCORE_BARRIER_WEIGHT" \
  TRACEQ_SCORE_CURRENT_BARRIER_WEIGHT="$SCORE_CURRENT_BARRIER_WEIGHT" \
  TRACEQ_SCORE_EXPOSURE_WINDOW_WEIGHT="$SCORE_EXPOSURE_WINDOW_WEIGHT" \
  TRACEQ_SCORE_EXPOSURE_VP_WEIGHT="$SCORE_EXPOSURE_VP_WEIGHT" \
  TRACEQ_SCORE_EXPOSURE_BEST_VP_WEIGHT="$SCORE_EXPOSURE_BEST_VP_WEIGHT" \
  TRACEQ_EXPOSURE_MIN_VP="$EXPOSURE_MIN_VP" \
  TRACEQ_EXPOSURE_MIN_MONSTER_HP="$EXPOSURE_MIN_MONSTER_HP" \
  TRACEQ_REQUIRE_EXPOSURE_DELTA="$REQUIRE_EXPOSURE_DELTA" \
  TRACEQ_SCORE_TARGET_QUALITY_WINDOW_WEIGHT="$SCORE_TARGET_QUALITY_WINDOW_WEIGHT" \
  TRACEQ_SCORE_TARGET_QUALITY_VP_WEIGHT="$SCORE_TARGET_QUALITY_VP_WEIGHT" \
  TRACEQ_SCORE_TARGET_QUALITY_BEST_VP_WEIGHT="$SCORE_TARGET_QUALITY_BEST_VP_WEIGHT" \
  TRACEQ_TARGET_QUALITY_MIN_VP="$TARGET_QUALITY_MIN_VP" \
  TRACEQ_REQUIRE_TARGET_QUALITY_DELTA="$REQUIRE_TARGET_QUALITY_DELTA" \
  TRACEQ_SCORE_STATUS_PENALTY="$SCORE_STATUS_PENALTY" \
  TRACEQ_FORBID_TYPES="$FORBID_TYPES" \
  TRACEQ_MAX_STATUS_LEVEL="$MAX_STATUS_LEVEL" \
  TRACEQ_PRESERVE_ROUTE_FIREPOWER="$PRESERVE_ROUTE_FIREPOWER" \
  TRACEQ_PRESERVE_ROUTE_SURVIVAL="$PRESERVE_ROUTE_SURVIVAL" \
  TRACEQ_ITERS="$ITERS" \
  TRACEQ_PLANNER_HORIZON="$PLANNER_HORIZON" \
  TRACEQ_VALUEW="$VALUEW" \
  TRACEQ_PROGRESS_EVERY="$PROGRESS_EVERY" \
  TRACEQ_OUT="$OUT_DIR/tracestateq.json" \
  TRACEQ_SUMMARY="$OUT_DIR/summary.json" \
  TRACEQ_DATA_OUT="$DATA_DIR/traceq.jsonl" \
  npx vitest run src/lib/play/ml/_tracestatecounterfactual.test.ts --disable-console-intercept \
  2>&1 | tee "$OUT_DIR/logs/tracestateq.log"

sample_count=0
if [[ -f "$DATA_DIR/traceq.jsonl" ]]; then
  sample_count="$(wc -l < "$DATA_DIR/traceq.jsonl" | tr -d ' ')"
fi
echo "traceq_samples=$sample_count" | tee "$OUT_DIR/logs/samples.log"

if [[ "$TRAIN" == "1" ]]; then
  if [[ "$sample_count" -lt "$MIN_TRAIN_SAMPLES" ]]; then
    echo "refusing train: samples=$sample_count < MIN_TRAIN_SAMPLES=$MIN_TRAIN_SAMPLES" >&2
    exit 3
  fi
  CUDA_VISIBLE_DEVICES="$GPU" ml/.venv/bin/python ml/train.py \
    --data "$DATA_DIR" \
    --out "$OUT_DIR/best_policy.json" \
    --mode alphazero \
    --init-from "$TRAIN_INIT_WEIGHTS" \
    --epochs "$TRAIN_EPOCHS" \
    --batch-size "$TRAIN_BATCH" \
    --lr "$TRAIN_LR" \
    --value-coef "$TRAIN_VALUE_COEF" \
    2>&1 | tee "$OUT_DIR/logs/train.log"
fi

echo "DONE: $OUT_DIR/summary.json"
REMOTE
status=$?
set -e

LOCAL_OUT_DIR="ml/meta_runs/$RUN_ID"
mkdir -p "$LOCAL_OUT_DIR"
rsync_status=0
rsync -az "$HOST:$REMOTE_DIR/ml/meta_runs/$RUN_ID/" "$LOCAL_OUT_DIR/" || rsync_status=$?
echo "$LOCAL_OUT_DIR"
if [[ "$status" -ne 0 ]]; then
  exit "$status"
fi
exit "$rsync_status"
