#!/usr/bin/env bash
set -euo pipefail

HOST="${ARC_BOT_GPU_HOST:-ubuntu@216.151.21.122}"
REMOTE_DIR="${ARC_BOT_REMOTE_DIR:-/data/share8/michaelvuaprilexperimentation/arc-bot}"
RUN_ID="${RUN_ID:-routeexecq-fullcontrol-$(date -u +%Y%m%dT%H%M%SZ)}"
GPU="${GPU:-7}"
MIN_FREE_MB="${MIN_FREE_MB:-1024}"

WEIGHTS="${WEIGHTS:-ml/meta_runs/aux-head-act52-medium-20260627T222453Z/best_policy.json}"
PATCH_NAV_WEIGHTS="${PATCH_NAV_WEIGHTS:-}"
PATCH_NAV_GATE="${PATCH_NAV_GATE:-all}"
PATCH2_NAV_WEIGHTS="${PATCH2_NAV_WEIGHTS:-}"
PATCH2_NAV_GATE="${PATCH2_NAV_GATE:-all}"
NAV_WEIGHTS="${NAV_WEIGHTS:-ml/meta_runs/routeq-nav-specialist-20260628T0305Z/best_policy.json}"
NAV_GATE="${NAV_GATE:-unsafe-firepower}"
SCALE_NAV_WEIGHTS="${SCALE_NAV_WEIGHTS:-}"
SCALE_NAV_GATE="${SCALE_NAV_GATE:-route-option-scaling}"
MICRO_WEIGHTS="${MICRO_WEIGHTS-ml/meta_runs/routeexecq-micro-20260628T0405Z/best_policy.json}"
MICRO_GATE="${MICRO_GATE:-location-interactions}"
PROFILES="${PROFILES:-pvphunter,medium,cultivator,survivor}"
PLANNER_PROFILE="${PLANNER_PROFILE:-cultivator}"
SOURCE_SEED_BASE="${SOURCE_SEED_BASE:-6500000}"
ALL_PLANNER_SEATS="${ALL_PLANNER_SEATS:-0}"

GAMES="${GAMES:-64}"
MAX_WINDOWS="${MAX_WINDOWS:-128}"
MAX_ROUNDS="${MAX_ROUNDS:-30}"
HORIZONS="${HORIZONS:-3,6,10}"
SELECT_HORIZON="${SELECT_HORIZON:-6}"
LABEL_HORIZON="${LABEL_HORIZON:-10}"
LABEL_SCORE_THRESHOLD="${LABEL_SCORE_THRESHOLD:-0.25}"
LABEL_VP_THRESHOLD="${LABEL_VP_THRESHOLD:-0}"
LABEL_STATUS_TOLERANCE="${LABEL_STATUS_TOLERANCE:-0}"
POSITIVE_ONLY_DATA="${POSITIVE_ONLY_DATA:-0}"
ROLLOUT_POLICY="${ROLLOUT_POLICY:-policy}"
BRANCH_SCOPE="${BRANCH_SCOPE:-location}"
BRANCH_TYPES="${BRANCH_TYPES:-}"
MIN_PLAYER_VP="${MIN_PLAYER_VP:-0}"
MAX_PLAYER_VP="${MAX_PLAYER_VP:-}"
MIN_ROUND="${MIN_ROUND:-0}"
MAX_ROUND="${MAX_ROUND:-}"
DESTINATIONS="${DESTINATIONS:-}"
MIN_MONSTER_HP="${MIN_MONSTER_HP:-0}"
MAX_MONSTER_HP="${MAX_MONSTER_HP:-}"
MIN_CLEAN_KILL_PROB="${MIN_CLEAN_KILL_PROB:-0}"
MAX_CLEAN_KILL_PROB="${MAX_CLEAN_KILL_PROB:-}"
MIN_FIREPOWER_KILL_PROB="${MIN_FIREPOWER_KILL_PROB:-0}"
MAX_FIREPOWER_KILL_PROB="${MAX_FIREPOWER_KILL_PROB:-}"
MIN_EXPECTED_ATTACK="${MIN_EXPECTED_ATTACK:-0}"
MIN_ATTACK_DICE="${MIN_ATTACK_DICE:-0}"
MIN_SPIRIT_ANIMAL="${MIN_SPIRIT_ANIMAL:-0}"
MIN_CULTIVATOR="${MIN_CULTIVATOR:-0}"
MIN_MAX_BARRIER="${MIN_MAX_BARRIER:-0}"

SCORE_VP_WEIGHT="${SCORE_VP_WEIGHT:-1}"
SCORE_CLEAN_OPPORTUNITY_WEIGHT="${SCORE_CLEAN_OPPORTUNITY_WEIGHT:-2}"
SCORE_FIREPOWER_OPPORTUNITY_WEIGHT="${SCORE_FIREPOWER_OPPORTUNITY_WEIGHT:-0.25}"
SCORE_EXPECTED_ATTACK_WEIGHT="${SCORE_EXPECTED_ATTACK_WEIGHT:-0.8}"
SCORE_ATTACK_DICE_WEIGHT="${SCORE_ATTACK_DICE_WEIGHT:-0.4}"
SCORE_SPIRIT_ANIMAL_WEIGHT="${SCORE_SPIRIT_ANIMAL_WEIGHT:-0.5}"
SCORE_CULTIVATOR_WEIGHT="${SCORE_CULTIVATOR_WEIGHT:-0}"
SCORE_BARRIER_WEIGHT="${SCORE_BARRIER_WEIGHT:-0.2}"
SCORE_CURRENT_BARRIER_WEIGHT="${SCORE_CURRENT_BARRIER_WEIGHT:-0}"
SCORE_KILL_WEIGHT="${SCORE_KILL_WEIGHT:-0}"
SCORE_REACH30_BONUS="${SCORE_REACH30_BONUS:-0}"
SCORE_STATUS_PENALTY="${SCORE_STATUS_PENALTY:-2}"

ITERS="${ITERS:-16}"
PLANNER_HORIZON="${PLANNER_HORIZON:-12}"
VALUEW="${VALUEW:-1}"
FULL_SELECTION="${FULL_SELECTION:-value}"
ROLLOUT_FULL_SELECTION="${ROLLOUT_FULL_SELECTION:-value}"
TIMEOUT="${TIMEOUT:-60m}"
PROGRESS_EVERY="${PROGRESS_EVERY:-1}"
PRESERVE_ROUTE_FIREPOWER="${PRESERVE_ROUTE_FIREPOWER:-0}"
PRESERVE_ROUTE_SURVIVAL="${PRESERVE_ROUTE_SURVIVAL:-0}"
FORBID_TYPES="${FORBID_TYPES:-initiatePvp}"
MAX_STATUS_LEVEL="${MAX_STATUS_LEVEL:-0}"

RUN_IMITATION="${RUN_IMITATION:-1}"
IMITATION_EPOCHS="${IMITATION_EPOCHS:-120}"
MIN_IMITATION_SAMPLES="${MIN_IMITATION_SAMPLES:-24}"

TRAIN="${TRAIN:-0}"
TRAIN_INIT_WEIGHTS="${TRAIN_INIT_WEIGHTS:-$WEIGHTS}"
MIN_TRAIN_SAMPLES="${MIN_TRAIN_SAMPLES:-1}"
TRAIN_EPOCHS="${TRAIN_EPOCHS:-8}"
TRAIN_BATCH="${TRAIN_BATCH:-256}"
TRAIN_LR="${TRAIN_LR:-0.0003}"
TRAIN_VALUE_COEF="${TRAIN_VALUE_COEF:-0.5}"

set +e
ssh -o BatchMode=yes -o ConnectTimeout=8 "$HOST" \
  REMOTE_DIR="$REMOTE_DIR" \
  RUN_ID="$RUN_ID" \
  GPU="$GPU" \
  MIN_FREE_MB="$MIN_FREE_MB" \
  WEIGHTS="$WEIGHTS" \
  PATCH_NAV_WEIGHTS="$PATCH_NAV_WEIGHTS" \
  PATCH_NAV_GATE="$PATCH_NAV_GATE" \
  PATCH2_NAV_WEIGHTS="$PATCH2_NAV_WEIGHTS" \
  PATCH2_NAV_GATE="$PATCH2_NAV_GATE" \
  NAV_WEIGHTS="$NAV_WEIGHTS" \
  NAV_GATE="$NAV_GATE" \
  SCALE_NAV_WEIGHTS="$SCALE_NAV_WEIGHTS" \
  SCALE_NAV_GATE="$SCALE_NAV_GATE" \
  MICRO_WEIGHTS="$MICRO_WEIGHTS" \
  MICRO_GATE="$MICRO_GATE" \
  PROFILES="$PROFILES" \
  PLANNER_PROFILE="$PLANNER_PROFILE" \
  SOURCE_SEED_BASE="$SOURCE_SEED_BASE" \
  ALL_PLANNER_SEATS="$ALL_PLANNER_SEATS" \
  GAMES="$GAMES" \
  MAX_WINDOWS="$MAX_WINDOWS" \
  MAX_ROUNDS="$MAX_ROUNDS" \
  HORIZONS="$HORIZONS" \
  SELECT_HORIZON="$SELECT_HORIZON" \
  LABEL_HORIZON="$LABEL_HORIZON" \
  LABEL_SCORE_THRESHOLD="$LABEL_SCORE_THRESHOLD" \
  LABEL_VP_THRESHOLD="$LABEL_VP_THRESHOLD" \
  LABEL_STATUS_TOLERANCE="$LABEL_STATUS_TOLERANCE" \
  POSITIVE_ONLY_DATA="$POSITIVE_ONLY_DATA" \
  ROLLOUT_POLICY="$ROLLOUT_POLICY" \
  BRANCH_SCOPE="$BRANCH_SCOPE" \
  BRANCH_TYPES="$BRANCH_TYPES" \
  MIN_PLAYER_VP="$MIN_PLAYER_VP" \
  MAX_PLAYER_VP="$MAX_PLAYER_VP" \
  MIN_ROUND="$MIN_ROUND" \
  MAX_ROUND="$MAX_ROUND" \
  DESTINATIONS="$DESTINATIONS" \
  MIN_MONSTER_HP="$MIN_MONSTER_HP" \
  MAX_MONSTER_HP="$MAX_MONSTER_HP" \
  MIN_CLEAN_KILL_PROB="$MIN_CLEAN_KILL_PROB" \
  MAX_CLEAN_KILL_PROB="$MAX_CLEAN_KILL_PROB" \
  MIN_FIREPOWER_KILL_PROB="$MIN_FIREPOWER_KILL_PROB" \
  MAX_FIREPOWER_KILL_PROB="$MAX_FIREPOWER_KILL_PROB" \
  MIN_EXPECTED_ATTACK="$MIN_EXPECTED_ATTACK" \
  MIN_ATTACK_DICE="$MIN_ATTACK_DICE" \
  MIN_SPIRIT_ANIMAL="$MIN_SPIRIT_ANIMAL" \
  MIN_CULTIVATOR="$MIN_CULTIVATOR" \
  MIN_MAX_BARRIER="$MIN_MAX_BARRIER" \
  SCORE_VP_WEIGHT="$SCORE_VP_WEIGHT" \
  SCORE_CLEAN_OPPORTUNITY_WEIGHT="$SCORE_CLEAN_OPPORTUNITY_WEIGHT" \
  SCORE_FIREPOWER_OPPORTUNITY_WEIGHT="$SCORE_FIREPOWER_OPPORTUNITY_WEIGHT" \
  SCORE_EXPECTED_ATTACK_WEIGHT="$SCORE_EXPECTED_ATTACK_WEIGHT" \
  SCORE_ATTACK_DICE_WEIGHT="$SCORE_ATTACK_DICE_WEIGHT" \
  SCORE_SPIRIT_ANIMAL_WEIGHT="$SCORE_SPIRIT_ANIMAL_WEIGHT" \
  SCORE_CULTIVATOR_WEIGHT="$SCORE_CULTIVATOR_WEIGHT" \
  SCORE_BARRIER_WEIGHT="$SCORE_BARRIER_WEIGHT" \
  SCORE_CURRENT_BARRIER_WEIGHT="$SCORE_CURRENT_BARRIER_WEIGHT" \
  SCORE_KILL_WEIGHT="$SCORE_KILL_WEIGHT" \
  SCORE_REACH30_BONUS="$SCORE_REACH30_BONUS" \
  SCORE_STATUS_PENALTY="$SCORE_STATUS_PENALTY" \
  ITERS="$ITERS" \
  PLANNER_HORIZON="$PLANNER_HORIZON" \
  VALUEW="$VALUEW" \
  FULL_SELECTION="$FULL_SELECTION" \
  ROLLOUT_FULL_SELECTION="$ROLLOUT_FULL_SELECTION" \
  TIMEOUT="$TIMEOUT" \
  PROGRESS_EVERY="$PROGRESS_EVERY" \
  PRESERVE_ROUTE_FIREPOWER="$PRESERVE_ROUTE_FIREPOWER" \
  PRESERVE_ROUTE_SURVIVAL="$PRESERVE_ROUTE_SURVIVAL" \
  FORBID_TYPES="$FORBID_TYPES" \
  MAX_STATUS_LEVEL="$MAX_STATUS_LEVEL" \
  RUN_IMITATION="$RUN_IMITATION" \
  IMITATION_EPOCHS="$IMITATION_EPOCHS" \
  MIN_IMITATION_SAMPLES="$MIN_IMITATION_SAMPLES" \
  TRAIN="$TRAIN" \
  TRAIN_INIT_WEIGHTS="$TRAIN_INIT_WEIGHTS" \
  MIN_TRAIN_SAMPLES="$MIN_TRAIN_SAMPLES" \
  TRAIN_EPOCHS="$TRAIN_EPOCHS" \
  TRAIN_BATCH="$TRAIN_BATCH" \
  TRAIN_LR="$TRAIN_LR" \
  TRAIN_VALUE_COEF="$TRAIN_VALUE_COEF" \
  bash -s <<'REMOTE'
set -euo pipefail

cd "$REMOTE_DIR"
if test -s "$HOME/.nvm/nvm.sh"; then
  # shellcheck disable=SC1090
  source "$HOME/.nvm/nvm.sh"
  nvm use 22 >/dev/null
fi

if command -v nvidia-smi >/dev/null 2>&1; then
  free_mb="$(nvidia-smi --query-gpu=memory.free --format=csv,noheader,nounits -i "$GPU" | head -n 1 | tr -dc '0-9')"
  used_mb="$(nvidia-smi --query-gpu=memory.used --format=csv,noheader,nounits -i "$GPU" | head -n 1 | tr -dc '0-9')"
  echo "gpu=$GPU free_mb=${free_mb:-unknown} used_mb=${used_mb:-unknown} min_free_mb=$MIN_FREE_MB"
  if [[ -n "${free_mb:-}" && "$free_mb" -lt "$MIN_FREE_MB" ]]; then
    echo "refusing routeexecq run: GPU $GPU has ${free_mb}MB free, below MIN_FREE_MB=$MIN_FREE_MB" >&2
    exit 2
  fi
fi

OUT_DIR="ml/meta_runs/$RUN_ID"
DATA_DIR="$OUT_DIR/data"
mkdir -p "$DATA_DIR" "$OUT_DIR/logs"

cat > "$OUT_DIR/config.json" <<JSON
{
  "run_id": "$RUN_ID",
  "mode": "routeexecq-full-control",
  "gpu": "$GPU",
  "min_free_mb": $MIN_FREE_MB,
  "weights": "$WEIGHTS",
  "patch_nav_weights": "$PATCH_NAV_WEIGHTS",
  "patch_nav_gate": "$PATCH_NAV_GATE",
  "patch2_nav_weights": "$PATCH2_NAV_WEIGHTS",
  "patch2_nav_gate": "$PATCH2_NAV_GATE",
  "nav_weights": "$NAV_WEIGHTS",
  "nav_gate": "$NAV_GATE",
  "scale_nav_weights": "$SCALE_NAV_WEIGHTS",
  "scale_nav_gate": "$SCALE_NAV_GATE",
  "micro_weights": "$MICRO_WEIGHTS",
  "micro_gate": "$MICRO_GATE",
  "profiles": "$PROFILES",
  "planner_profile": "$PLANNER_PROFILE",
  "source_seed_base": $SOURCE_SEED_BASE,
  "all_planner_seats": $ALL_PLANNER_SEATS,
  "games": $GAMES,
  "max_windows": $MAX_WINDOWS,
  "max_rounds": $MAX_ROUNDS,
  "horizons": "$HORIZONS",
  "select_horizon": $SELECT_HORIZON,
  "label_horizon": $LABEL_HORIZON,
  "label_score_threshold": $LABEL_SCORE_THRESHOLD,
  "label_vp_threshold": $LABEL_VP_THRESHOLD,
  "label_status_tolerance": $LABEL_STATUS_TOLERANCE,
  "positive_only_data": $POSITIVE_ONLY_DATA,
  "rollout_policy": "$ROLLOUT_POLICY",
  "branch_scope": "$BRANCH_SCOPE",
  "branch_types": "$BRANCH_TYPES",
  "min_player_vp": $MIN_PLAYER_VP,
  "max_player_vp": "${MAX_PLAYER_VP}",
  "min_round": $MIN_ROUND,
  "max_round": "${MAX_ROUND}",
  "destinations": "$DESTINATIONS",
  "min_monster_hp": $MIN_MONSTER_HP,
  "max_monster_hp": "${MAX_MONSTER_HP}",
  "min_clean_kill_prob": $MIN_CLEAN_KILL_PROB,
  "max_clean_kill_prob": "${MAX_CLEAN_KILL_PROB}",
  "min_firepower_kill_prob": $MIN_FIREPOWER_KILL_PROB,
  "max_firepower_kill_prob": "${MAX_FIREPOWER_KILL_PROB}",
  "min_expected_attack": $MIN_EXPECTED_ATTACK,
  "min_attack_dice": $MIN_ATTACK_DICE,
  "min_spirit_animal": $MIN_SPIRIT_ANIMAL,
  "min_cultivator": $MIN_CULTIVATOR,
  "min_max_barrier": $MIN_MAX_BARRIER,
  "score_weights": {
    "vp": $SCORE_VP_WEIGHT,
    "clean_opportunity": $SCORE_CLEAN_OPPORTUNITY_WEIGHT,
    "firepower_opportunity": $SCORE_FIREPOWER_OPPORTUNITY_WEIGHT,
    "expected_attack": $SCORE_EXPECTED_ATTACK_WEIGHT,
    "attack_dice": $SCORE_ATTACK_DICE_WEIGHT,
    "spirit_animal": $SCORE_SPIRIT_ANIMAL_WEIGHT,
    "cultivator": $SCORE_CULTIVATOR_WEIGHT,
    "barrier": $SCORE_BARRIER_WEIGHT,
    "current_barrier": $SCORE_CURRENT_BARRIER_WEIGHT,
    "kill": $SCORE_KILL_WEIGHT,
    "reach30_bonus": $SCORE_REACH30_BONUS,
    "status_penalty": $SCORE_STATUS_PENALTY
  },
  "iters": $ITERS,
  "planner_horizon": $PLANNER_HORIZON,
  "value_weight": $VALUEW,
  "full_selection": "$FULL_SELECTION",
  "rollout_full_selection": "$ROLLOUT_FULL_SELECTION",
  "progress_every": $PROGRESS_EVERY,
  "preserve_route_firepower": "$PRESERVE_ROUTE_FIREPOWER",
  "preserve_route_survival": "$PRESERVE_ROUTE_SURVIVAL",
  "forbid_types": "$FORBID_TYPES",
  "max_status_level": "$MAX_STATUS_LEVEL",
  "run_imitation": $RUN_IMITATION,
  "train": $TRAIN,
  "train_init_weights": "$TRAIN_INIT_WEIGHTS",
  "min_train_samples": $MIN_TRAIN_SAMPLES
}
JSON

timeout "$TIMEOUT" env \
  CUDA_VISIBLE_DEVICES="$GPU" \
  ROUTEEXECQ=1 \
  ROUTEEXECQ_SOURCE=full-control \
  ROUTEEXECQ_GAMES="$GAMES" \
  ROUTEEXECQ_MAX_WINDOWS="$MAX_WINDOWS" \
  ROUTEEXECQ_MAXROUNDS="$MAX_ROUNDS" \
  ROUTEEXECQ_HORIZONS="$HORIZONS" \
  ROUTEEXECQ_SELECT_HORIZON="$SELECT_HORIZON" \
  ROUTEEXECQ_LABEL_HORIZON="$LABEL_HORIZON" \
  ROUTEEXECQ_LABEL_SCORE_THRESHOLD="$LABEL_SCORE_THRESHOLD" \
  ROUTEEXECQ_LABEL_VP_THRESHOLD="$LABEL_VP_THRESHOLD" \
  ROUTEEXECQ_LABEL_STATUS_TOLERANCE="$LABEL_STATUS_TOLERANCE" \
  ROUTEEXECQ_POSITIVE_ONLY_DATA="$POSITIVE_ONLY_DATA" \
  ROUTEEXECQ_ROLLOUT_POLICY="$ROLLOUT_POLICY" \
  ROUTEEXECQ_BRANCH_SCOPE="$BRANCH_SCOPE" \
  ROUTEEXECQ_BRANCH_TYPES="$BRANCH_TYPES" \
  ROUTEEXECQ_MIN_PLAYER_VP="$MIN_PLAYER_VP" \
  ROUTEEXECQ_MAX_PLAYER_VP="$MAX_PLAYER_VP" \
  ROUTEEXECQ_MIN_ROUND="$MIN_ROUND" \
  ROUTEEXECQ_MAX_ROUND="$MAX_ROUND" \
  ROUTEEXECQ_DESTINATIONS="$DESTINATIONS" \
  ROUTEEXECQ_MIN_MONSTER_HP="$MIN_MONSTER_HP" \
  ROUTEEXECQ_MAX_MONSTER_HP="$MAX_MONSTER_HP" \
  ROUTEEXECQ_MIN_CLEAN_KILL_PROB="$MIN_CLEAN_KILL_PROB" \
  ROUTEEXECQ_MAX_CLEAN_KILL_PROB="$MAX_CLEAN_KILL_PROB" \
  ROUTEEXECQ_MIN_FIREPOWER_KILL_PROB="$MIN_FIREPOWER_KILL_PROB" \
  ROUTEEXECQ_MAX_FIREPOWER_KILL_PROB="$MAX_FIREPOWER_KILL_PROB" \
  ROUTEEXECQ_MIN_EXPECTED_ATTACK="$MIN_EXPECTED_ATTACK" \
  ROUTEEXECQ_MIN_ATTACK_DICE="$MIN_ATTACK_DICE" \
  ROUTEEXECQ_MIN_SPIRIT_ANIMAL="$MIN_SPIRIT_ANIMAL" \
  ROUTEEXECQ_MIN_CULTIVATOR="$MIN_CULTIVATOR" \
  ROUTEEXECQ_MIN_MAX_BARRIER="$MIN_MAX_BARRIER" \
  ROUTEEXECQ_SCORE_VP_WEIGHT="$SCORE_VP_WEIGHT" \
  ROUTEEXECQ_SCORE_CLEAN_OPPORTUNITY_WEIGHT="$SCORE_CLEAN_OPPORTUNITY_WEIGHT" \
  ROUTEEXECQ_SCORE_FIREPOWER_OPPORTUNITY_WEIGHT="$SCORE_FIREPOWER_OPPORTUNITY_WEIGHT" \
  ROUTEEXECQ_SCORE_EXPECTED_ATTACK_WEIGHT="$SCORE_EXPECTED_ATTACK_WEIGHT" \
  ROUTEEXECQ_SCORE_ATTACK_DICE_WEIGHT="$SCORE_ATTACK_DICE_WEIGHT" \
  ROUTEEXECQ_SCORE_SPIRIT_ANIMAL_WEIGHT="$SCORE_SPIRIT_ANIMAL_WEIGHT" \
  ROUTEEXECQ_SCORE_CULTIVATOR_WEIGHT="$SCORE_CULTIVATOR_WEIGHT" \
  ROUTEEXECQ_SCORE_BARRIER_WEIGHT="$SCORE_BARRIER_WEIGHT" \
  ROUTEEXECQ_SCORE_CURRENT_BARRIER_WEIGHT="$SCORE_CURRENT_BARRIER_WEIGHT" \
  ROUTEEXECQ_SCORE_KILL_WEIGHT="$SCORE_KILL_WEIGHT" \
  ROUTEEXECQ_SCORE_REACH30_BONUS="$SCORE_REACH30_BONUS" \
  ROUTEEXECQ_SCORE_STATUS_PENALTY="$SCORE_STATUS_PENALTY" \
  ROUTEEXECQ_WEIGHTS="$WEIGHTS" \
  ROUTEEXECQ_PATCH_NAV_WEIGHTS="$PATCH_NAV_WEIGHTS" \
  ROUTEEXECQ_PATCH_NAV_GATE="$PATCH_NAV_GATE" \
  ROUTEEXECQ_PATCH2_NAV_WEIGHTS="$PATCH2_NAV_WEIGHTS" \
  ROUTEEXECQ_PATCH2_NAV_GATE="$PATCH2_NAV_GATE" \
  ROUTEEXECQ_NAV_WEIGHTS="$NAV_WEIGHTS" \
  ROUTEEXECQ_NAV_GATE="$NAV_GATE" \
  ROUTEEXECQ_SCALE_NAV_WEIGHTS="$SCALE_NAV_WEIGHTS" \
  ROUTEEXECQ_SCALE_NAV_GATE="$SCALE_NAV_GATE" \
  ROUTEEXECQ_MICRO_WEIGHTS="$MICRO_WEIGHTS" \
  ROUTEEXECQ_MICRO_GATE="$MICRO_GATE" \
  ROUTEEXECQ_PROFILES="$PROFILES" \
  ROUTEEXECQ_PLANNER_PROFILE="$PLANNER_PROFILE" \
  ROUTEEXECQ_SOURCE_SEED_BASE="$SOURCE_SEED_BASE" \
  ROUTEEXECQ_ALL_PLANNER_SEATS="$ALL_PLANNER_SEATS" \
  ROUTEEXECQ_ITERS="$ITERS" \
  ROUTEEXECQ_PLANNER_HORIZON="$PLANNER_HORIZON" \
  ROUTEEXECQ_VALUEW="$VALUEW" \
  ROUTEEXECQ_FULL_SELECTION="$FULL_SELECTION" \
  ROUTEEXECQ_ROLLOUT_FULL_SELECTION="$ROLLOUT_FULL_SELECTION" \
  ROUTEEXECQ_PROGRESS_EVERY="$PROGRESS_EVERY" \
  ROUTEEXECQ_PRESERVE_ROUTE_FIREPOWER="$PRESERVE_ROUTE_FIREPOWER" \
  ROUTEEXECQ_PRESERVE_ROUTE_SURVIVAL="$PRESERVE_ROUTE_SURVIVAL" \
  ROUTEEXECQ_FORBID_TYPES="$FORBID_TYPES" \
  ROUTEEXECQ_MAX_STATUS_LEVEL="$MAX_STATUS_LEVEL" \
  ROUTEEXECQ_OUT="$OUT_DIR/routeexecq.json" \
  ROUTEEXECQ_SUMMARY="$OUT_DIR/summary.json" \
  ROUTEEXECQ_DATA_OUT="$DATA_DIR/routeexecq.jsonl" \
  npx vitest run src/lib/play/ml/_routeexecutioncounterfactual.test.ts --disable-console-intercept \
  2>&1 | tee "$OUT_DIR/logs/routeexecq.log"

sample_count="$(wc -l < "$DATA_DIR/routeexecq.jsonl" | tr -d ' ')"
if [[ "$RUN_IMITATION" == "1" && "$sample_count" -ge "$MIN_IMITATION_SAMPLES" ]]; then
  set +e
  CUDA_VISIBLE_DEVICES="$GPU" ml/.venv/bin/python ml/route_imitation.py \
    --data "$DATA_DIR" \
    --out "$OUT_DIR/route_imitation_summary.json" \
    --epochs "$IMITATION_EPOCHS" \
    2>&1 | tee "$OUT_DIR/logs/route_imitation.log"
  imitation_status="${PIPESTATUS[0]}"
  set -e
  if [[ "$imitation_status" -ne 0 ]]; then
    echo "route imitation diagnostic exited $imitation_status; continuing to TRAIN=$TRAIN" | tee -a "$OUT_DIR/logs/route_imitation.log"
  fi
elif [[ "$RUN_IMITATION" == "1" ]]; then
  echo "skip route imitation: samples=$sample_count < MIN_IMITATION_SAMPLES=$MIN_IMITATION_SAMPLES" | tee "$OUT_DIR/logs/route_imitation.log"
fi

if [[ "$TRAIN" == "1" ]]; then
  if [[ "$sample_count" -lt "$MIN_TRAIN_SAMPLES" ]]; then
    echo "refusing train: samples=$sample_count < MIN_TRAIN_SAMPLES=$MIN_TRAIN_SAMPLES" >&2
    exit 3
  fi
  CUDA_VISIBLE_DEVICES="$GPU" ml/.venv/bin/python ml/train.py \
    --data "$DATA_DIR" \
    --out "$OUT_DIR/best_policy.json" \
    --mode alphazero \
    --init-from "$TRAIN_INIT_WEIGHTS" \
    --epochs "$TRAIN_EPOCHS" \
    --batch-size "$TRAIN_BATCH" \
    --lr "$TRAIN_LR" \
    --value-coef "$TRAIN_VALUE_COEF" \
    2>&1 | tee "$OUT_DIR/logs/train.log"
fi

echo "DONE: $OUT_DIR/summary.json"
REMOTE
status=$?
set -e

LOCAL_OUT_DIR="ml/meta_runs/$RUN_ID"
mkdir -p "$LOCAL_OUT_DIR"
rsync_status=0
rsync -az "$HOST:$REMOTE_DIR/ml/meta_runs/$RUN_ID/" "$LOCAL_OUT_DIR/" || rsync_status=$?
echo "$LOCAL_OUT_DIR"
if [[ "$status" -ne 0 ]]; then
  exit "$status"
fi
exit "$rsync_status"
